export const FETCH_POSTS_DISPATCH = 'FETCH_POSTS_DISPATCH'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'

export const FETCH_POST_DISPATCH = 'FETCH_POST_DISPATCH'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL'

export const DELETE_POST_DISPATCH = 'DELETE_POST_DISPATCH'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
export const DELETE_POST_RESET = 'DELETE_POST_RESET'

export const EDIT_POST_DISPATCH = 'EDIT_POST_DISPATCH'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'
export const EDIT_POST_RESET = 'EDIT_POST_RESET'

export const ADD_POST_DISPATCH = 'ADD_POST_DISPATCH'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'
export const ADD_POST_RESET = 'ADD_POST_RESET'