export const FETCH_USERS_DISPATCH = 'FETCH_USERS_DISPATCH'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const FETCH_USER_DISPATCH = 'FETCH_USER_DISPATCH'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const DELETE_USER_DISPATCH = 'DELETE_USER_DISPATCH'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'

export const EDIT_USER_DISPATCH = 'EDIT_USER_DISPATCH'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL'
export const EDIT_USER_RESET = 'EDIT_USER_RESET'

export const ADD_USER_DISPATCH = 'ADD_USER_DISPATCH'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_USER_RESET = 'ADD_USER_RESET'